### ISSUE TITLE
Question: why not to commit before dispose if not commited already?

### ISSUE THREAD

**Issue by 474D** [lawrence-laz/transactional-io#2]
Nvm, I did really miss important thing :) exception. My bad... 👀
>  am just curious, since stream implements IDisposable and IAsyncDisposable, why not to commit before disposing, if it's not already commited? Then the clients would not need to explicitly commit if they don't want to :)
> 
> Or am I missing something important?
>

**Comment by lawrence-laz** [comment]
Yeah, explicit commit is required to roll back on exceptions.

Also, `.Commit()` only marks the stream to be committed, the actual commit logic and closing of the stream occurs when the stream is disposed. At first, I had implemented everything to be completed immediately when the `.Commit()` is called, but then I found out that some stream writers have buffers, which are flushed on dispose, so closing the file stream before it's disposed was leaving those stream writers hanging.

Have you found some use for this library? If you have any thoughts for improvements or face any issues, let me know, I am happy to collaborate :smiley:
